<?php

declare(strict_types=1);

namespace Resellerclub\Api;

use Resellerclub\Http\HttpMethod;

/**
 * Customer-related API calls.
 *
 * @see https://manage.resellerclub.com/kb/node/804
 */
final class Customer extends AbstractApi
{
  /**
   * Create a customer account.
   *
   * @see https://manage.resellerclub.com/kb/answer/804
   *
   * @param array<string, mixed> $customerDetails
   */
  public function createCustomer(array $customerDetails): mixed
  {
    $this->validator->validateCustomer($customerDetails);

    return $this->call(HttpMethod::Post, 'customers', 'signup', $customerDetails);
  }

  /**
   * Modify a customer account.
   *
   * @see https://manage.resellerclub.com/kb/answer/805
   *
   * @param array<string, mixed> $customerDetails
   */
  public function editCustomer(int|string $customerId, array $customerDetails): mixed
  {
    $customerDetails['customer-id'] = $customerId;
    $this->validator->validateCustomer($customerDetails);

    return $this->call(HttpMethod::Post, 'customers', 'modify', $customerDetails);
  }

  /**
   * Get customer details by username (email).
   *
   * @see https://manage.resellerclub.com/kb/answer/874
   */
  public function getCustomerByUserName(string $userName): mixed
  {
    $params = ['username' => $userName];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Get, 'customers', 'details', $params);
  }

  /**
   * Get customer details by customer ID.
   */
  public function getCustomerByCustomerId(int|string $customerId): mixed
  {
    $params = ['customer-id' => $customerId];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Get, 'customers', 'details-by-id', $params);
  }

  /**
   * Authenticate a customer, returning an authentication token.
   *
   * @see https://manage.resellerclub.com/kb/answer/818
   */
  public function generateToken(string $userName, string $password, string $ip): mixed
  {
    $params = ['username' => $userName, 'passwd' => $password, 'ip' => $ip];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'generate-token', $params);
  }

  /**
   * Authenticate a token generated by {@see generateToken()}.
   */
  public function authenticateToken(string $token): mixed
  {
    $params = ['token' => $token];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'authenticate-token', $params);
  }

  /**
   * Change a customer's password.
   *
   * @see https://manage.resellerclub.com/kb/answer/806
   */
  public function changePassword(int|string $customerId, string $newPassword): mixed
  {
    $params = ['customer-id' => $customerId, 'new-passwd' => $newPassword];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'change-password', $params);
  }

  /**
   * Generate a temporary password for a customer.
   *
   * @see https://manage.resellerclub.com/kb/answer/1648
   */
  public function generateTemporaryPassword(int|string $customerId): mixed
  {
    $params = ['customer-id' => $customerId];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'temp-password', $params);
  }

  /**
   * Search for customers matching the given criteria.
   *
   * @see https://manage.resellerclub.com/kb/answer/1270
   *
   * @param array<string, mixed> $criteria
   */
  public function searchCustomer(array $criteria, int $count = 10, int $page = 1): mixed
  {
    $criteria['no-of-records'] = $count;
    $criteria['page-no'] = $page;
    $this->validator->validate($criteria);

    return $this->call(HttpMethod::Get, 'customers', 'search', $criteria);
  }

  /**
   * Send a forgot-password email to a customer.
   *
   * @see https://manage.resellerclub.com/kb/answer/2410
   */
  public function forgotPassword(string $userName): mixed
  {
    $params = ['forgot-password' => $userName];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'forgot-password', $params);
  }

  /**
   * Delete a customer that has no active orders.
   *
   * @see https://manage.resellerclub.com/kb/answer/886
   */
  public function deleteCustomer(int|string $customerId): mixed
  {
    $params = ['customer-id' => $customerId];
    $this->validator->validate($params);

    return $this->call(HttpMethod::Post, 'customers', 'delete', $params);
  }
}
